const projects=[{"category":"Real Estate","file":"e6db1f61a051f43bc18bf354848469e9","name":"Hearthstone Residences"},{"category":"Real Estate","file":"e8b86c66c330805383f0e959a3ddf62e","name":"Meridian Estates"},{"category":"Real Estate","file":"350df4862c311359e3b2d73a70def40d","name":"Maison District"},{"category":"Real Estate","file":"71ee459145213f12db9cb19d80ed70db","name":"Skyline Homes"},{"category":"Interior Design","file":"0e43c209970a9a056b63625c25bbb2e8","name":"Godfrey Interiors"},{"category":"Interior Design","file":"05b69515f516febeb7cdfcf126ec8111","name":"Havenline Interiors"},{"category":"Food & Restaurant","file":"f536d3bb196e74e6d90da3b13fafbc31","name":"Saffron Grove"},{"category":"Food & Restaurant","file":"2c3f9fef98a776a580221f482afe9ab9","name":"Ember Grill"},{"category":"Food & Restaurant","file":"38aeec3ebd7b0ac652a0fbc31c72772b","name":"Verdant Table"},{"category":"Food & Restaurant","file":"e4e6937d4324d281215aac09b096b492","name":"Harvest Kitchen"},{"category":"Roofing","file":"3c266c6188d59cb339600af787b520e2","name":"Roofify Solutions"},{"category":"Roofing","file":"29de99ad9456db20ac8572d4bd0b4bf2","name":"PrimeRoof Services"},{"category":"Roofing","file":"861c6ee831d5b78e6ce648c890e59eb1","name":"Akay Roofing"},{"category":"Home Services","file":"bf54eab207e1a0dcd4a94b7dadf5c083","name":"ClearNest Cleaning"},{"category":"Home Services","file":"c8658cfd7a455fe4a9825938a09d48bd","name":"SwiftFix Home Services"},{"category":"Home Services","file":"a4e18d2987fa62a48eee14fb13915320","name":"ShieldGuard Pest Control"},{"category":"Home Services","file":"b9005f61b615b49943607b564574e126","name":"VoltEdge Electrical"},{"category":"Home Services","file":"686184eb66aa7649c595d9f7c218f675","name":"SecureVolt Electrical"},{"category":"Home Services","file":"d43b381dca68e03750fa322187684192","name":"FlowCraft Plumbing"},{"category":"Healthcare","file":"be7dfab34d8e5e5b01ef431301d3f008","name":"CareBridge Support"},{"category":"Healthcare","file":"723e45713d65756bd91ec1dad7a053da","name":"BrightImplant Dental Clinic"},{"category":"Healthcare","file":"65681935e8344c568e5ce7123e5315cf","name":"Dentora Dental Care"},{"category":"Healthcare","file":"9567eff912c4329b6a9f2fd2a490d905","name":"AuroCare Healthcare"},{"category":"Healthcare","file":"f6e2808f66c494a3b8c17941cba845db","name":"Dr. Care Medical Centre"}];
const socials=[["WhatsApp","https://wa.me/601172508348","<path d='M20 11.5a8.5 8.5 0 0 1-12.7 7.4L3 20l1.2-4.1A8.5 8.5 0 1 1 20 11.5Z' fill='none' stroke='currentColor' stroke-width='1.7'/><path d='M8 7c-2 3 3 8 6 7l1-2-2-1-1 1-2-2 1-1-1-2Z'/>"],["LinkedIn","https://www.linkedin.com/in/alalif-akash-ai-saas-founder/","<path d='M5 8H2v13h3ZM3.5 2a1.8 1.8 0 1 0 0 3.6 1.8 1.8 0 0 0 0-3.6ZM9 8v13h3v-7c0-4 5-4 5 0v7h3v-8c0-6-6-6-8-3V8Z'/>"],["Instagram","https://www.instagram.com/akash.decoder/","<rect x='3' y='3' width='18' height='18' rx='5' fill='none' stroke='currentColor' stroke-width='1.8'/><circle cx='12' cy='12' r='4' fill='none' stroke='currentColor' stroke-width='1.8'/><circle cx='17.5' cy='6.5' r='1'/>"],["Threads","https://www.threads.com/@akash.decoder","<text x='2' y='19' font-size='23' font-family='Arial' font-weight='bold'>@</text>"],["Email","mailto:akashalalif99@gmail.com","<rect x='2' y='4' width='20' height='16' rx='3' fill='none' stroke='currentColor' stroke-width='1.8'/><path d='m3 6 9 7 9-7' fill='none' stroke='currentColor' stroke-width='1.8'/>"]];
document.querySelector('.social-dock').innerHTML=socials.map(([name,url,icon])=>'<a href="'+url+'" target="_blank" rel="noopener" aria-label="'+name+'"><svg viewBox="0 0 24 24" aria-hidden="true">'+icon+'</svg></a>').join('');
document.querySelector('#footer-socials').innerHTML=socials.slice(0,4).map(([name,url])=>'<a href="'+url+'" target="_blank" rel="noopener">'+name+'</a>').join('');
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let count=0;document.querySelectorAll('.project').forEach(card=>{card.hidden=button.dataset.filter!=='All'&&card.dataset.category!==button.dataset.filter;if(!card.hidden)count++;});document.querySelector('#result-count').textContent='Showing '+count+' projects';}));
const dialog=document.querySelector('#project-dialog');let lastTrigger;
document.querySelectorAll('.project-open').forEach(button=>button.addEventListener('click',()=>{const p=projects[Number(button.dataset.index)];lastTrigger=button;document.querySelector('#dialog-title').textContent=p.name;document.querySelector('#dialog-category').textContent=p.category;document.querySelector('#dialog-image').src='assets/'+p.file+'.jpg';document.querySelector('#dialog-image').alt=p.name+' full design preview';dialog.showModal();document.body.classList.add('modal-open');}));
document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastTrigger?.focus();});
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');}));
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
function revealElement(el,delay=0){if(reducedMotion.matches)return;el.getAnimations().forEach(a=>a.cancel());el.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:700,delay,easing:'cubic-bezier(.22,1,.36,1)',fill:'backwards'});}
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){revealElement(e.target);observer.unobserve(e.target);}}),{threshold:0,rootMargin:'0px 0px 35px 0px'});document.querySelectorAll('.section-heading,.service,.about,.contact').forEach(el=>observer.observe(el));}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.project:not([hidden])').forEach((card,i)=>revealElement(card,Math.min(i,5)*35));}));
dialog.addEventListener('toggle',()=>{if(dialog.open)revealElement(dialog);});
const follow=document.createElement('aside');
follow.className='hero-follow';follow.setAttribute('aria-label','Al Alif Akash, project contact');follow.inert=true;follow.setAttribute('aria-hidden','true');
follow.innerHTML='<a class="hero-follow-copy" href="#home"><strong>Al Alif Akash</strong><small>Web Designer and AI SaaS Founder</small></a><a class="button" href="https://forms.gle/Cgne5ZoYGzKvzLfH9" target="_blank" rel="noopener">Start Your Project</a><img src="assets/portrait.webp" alt="" width="86" height="82">';
document.body.append(follow);
const hero=document.querySelector('.hero');let scrollFrame=0,following=false,heroEnd=0;
function measureHero(){heroEnd=hero.getBoundingClientRect().bottom+window.scrollY;updateFollow();}
function updateFollow(){scrollFrame=0;const next=window.scrollY>heroEnd-145;if(next===following)return;following=next;follow.classList.toggle('visible',next);follow.inert=!next;follow.setAttribute('aria-hidden',String(!next));if(!next&&follow.contains(document.activeElement)){document.querySelector('.brand').focus();}}
window.addEventListener('scroll',()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(updateFollow);},{passive:true});
window.addEventListener('resize',measureHero,{passive:true});
if('ResizeObserver'in window)new ResizeObserver(measureHero).observe(hero);
document.fonts.ready.then(measureHero);measureHero();
